submap_service: "/elevation_mapping/get_grid_map"
use_raw_map: false # Boolean to switch between raw and fused map.
map_frame_id: "odom"     # Must be the same as the input elevation submap.
robot_frame_id: "base_link"
min_update_rate: 0.2
map_center_x: 0.0
map_center_y: 0.0
map_length_x: 5.0
map_length_y: 5.0
footprint_yaw: 0.7854
max_gap_width: 0.3
grid_map_to_initialize_traversability_map: # Accept grid map to initial traversability map.
  enable: true
  # grid_map_topic_name: "initial_elevation_map"
  grid_map_topic_name: "elevation_mapping/elevation_map"
