# Footprint parameters
footprint:
  footprint_polygon: [[0.45, 0.30], [0.45, -0.30], [-0.45, -0.30], [-0.45, 0.30]] # Vertices of footprint polygon with coordinates [x, y] in robot footprint frame.
  circular_footprint_radius: 0.2
  circular_footprint_radius_inscribed: 0.30
  circular_footprint_offset: 0.05
  footprint_frame_id: foot_print
  traversability_default: 0.72 # Defines the default value for traversability of unknown regions in the traversability map.
  verify_roughness_footprint: false
  check_robot_inclination: false
